[build]
  command = "npm run build && npx next export"
  publish = "out"
  # Netlify's Next.js runtime plugin handles routing & server functions
[[plugins]]
  package = "@netlify/plugin-nextjs@latest"
