[build]
  command = "npm run build"
  publish = "out"
  # Netlify's Next.js runtime plugin handles routing & server functions
[[plugins]]
  package = "@netlify/plugin-nextjs"
  pinned_version = "5.14.3"
